# Configuration for sentry-craft (https://github.com/getsentry/craft)
minVersion: "0.9.2"
github:
  owner: getsentry
  repo: rust-proguard
targets:
  - name: crates
  - name: github
changelogPolicy: simple
statusProvider:
  name: github
artifactProvider:
  name: none
