[package]
name = "proguard"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]

[dependencies]
regex = "0.2.2"
memmap = "^0.5.0"
error-chain = "^0.9.0"
lazy_static = "^0.2.2"
